language: objective-c
osx_image: xcode7.3 
xcode_project: ios/sdk/aftershipsdk/aftership.xcodeproj #3
xcode_scheme: aftership #4
xcode_sdk: iphonesimulator9.3 #5
before_install:
 - gem install slather --no-rdoc --no-ri --no-document --quiet
after_success:
 - slather